config/routes.rb
PinewoodDerby::Application.routes.draw do
  resources :summaries

  resources :races

  resources :scouts

end

app/models/summary.rb
class Summary < ActiveRecord::Base
  
  set_table_name :race_summary
  
  set_primary_key :scout_id
  
  def readonly?
    return true
  end
  
  belongs_to :scout,
             :class_name => "Scout",
             :foreign_key => "scout_id"
  
end

app/controllers/summaries_controller.rb
class SummariesController < ApplicationController
  # GET /summaries
  # GET /summaries.json
  def index
    @summaries = Summary.find(:all, :order => "wins DESC, losses, differential DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @summaries }
    end
  end

  # GET /summaries/1
  # GET /summaries/1.json
  def show
    @summary = Summary.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @summary }
    end
  end

  # GET /summaries/new
  # GET /summaries/new.json
  def new
    @summary = Summary.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @summary }
    end
  end

  # GET /summaries/1/edit
  def edit
    @summary = Summary.find(params[:id])
  end

  # POST /summaries
  # POST /summaries.json
  def create
    @summary = Summary.new(params[:summary])

    respond_to do |format|
      if @summary.save
        format.html { redirect_to @summary, notice: 'Summary was successfully created.' }
        format.json { render json: @summary, status: :created, location: @summary }
      else
        format.html { render action: "new" }
        format.json { render json: @summary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /summaries/1
  # PUT /summaries/1.json
  def update
    @summary = Summary.find(params[:id])

    respond_to do |format|
      if @summary.update_attributes(params[:summary])
        format.html { redirect_to @summary, notice: 'Summary was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @summary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /summaries/1
  # DELETE /summaries/1.json
  def destroy
    @summary = Summary.find(params[:id])
    @summary.destroy

    respond_to do |format|
      format.html { redirect_to summaries_url }
      format.json { head :ok }
    end
  end
end

app/helpers/summaries_helper.rb
module SummariesHelper
end

app/views/summaries/_form.html.erb
<%= form_for(@summary) do |f| %>
  <% if @summary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@summary.errors.count, "error") %> prohibited this summary from being saved:</h2>

      <ul>
      <% @summary.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :scout_id %><br />
    <%= f.number_field :scout_id %>
  </div>
  <div class="field">
    <%= f.label :wins %><br />
    <%= f.number_field :wins %>
  </div>
  <div class="field">
    <%= f.label :losses %><br />
    <%= f.number_field :losses %>
  </div>
  <div class="field">
    <%= f.label :differential %><br />
    <%= f.number_field :differential %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/summaries/edit.html.erb
<h1>Editing Race Summary</h1>

<%= render 'form' %>

<%= link_to 'Show', @summary %> |
<%= link_to 'Back', summaries_path %>

app/views/summaries/index.html.erb
<h1>Race Summary</h1>

<table>
  <tr>
    <th>Scout</th>
    <th>Record</th>
    <th>Time Differential</th>
  </tr>

<% @summaries.each do |summary| %>
  <tr>
    <td><%= summary.scout.name %></td>
    <td><%= summary.wins %> - <%= summary.losses %></td>
    <td><%= summary.differential %></td>
  </tr>
<% end %>
</table>

app/views/summaries/new.html.erb
<h1>New summary</h1>

<%= render 'form' %>

<%= link_to 'Back', summaries_path %>

app/views/summaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Scout:</b>
  <%= @summary.scout_id %>
</p>

<p>
  <b>Wins:</b>
  <%= @summary.wins %>
</p>

<p>
  <b>Losses:</b>
  <%= @summary.losses %>
</p>

<p>
  <b>Differential:</b>
  <%= @summary.differential %>
</p>


<%= link_to 'Edit', edit_summary_path(@summary) %> |
<%= link_to 'Back', summaries_path %>