config/routes.rb
PinewoodDerby::Application.routes.draw do
  resources :summaries

  resources :races

  resources :scouts

end

app/models/race.rb
class Race < ActiveRecord::Base
  
  # id, heat, scout_1, scout_2, time1, time2
  
  belongs_to :scout_1,
             :class_name => "Scout",
             :foreign_key => "scout_1_id"
  
  belongs_to :scout_2,
             :class_name => "Scout",
             :foreign_key => "scout_2_id"

  after_initialize :init
  
  def init
    self.time1 ||= 0
    self.time2 ||= 0
  end
  
  def winner
    if time1 < time2 then
      scout_1
    elsif time2 < time1 then
      scout_2
    else
      nil
    end
  end
  
  def winner_name
    if winner.nil? then 
      ""
    else
      winner.name
    end
  end
  
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  # GET /races
  # GET /races.json
  def index
    @races = Race.find( :all, :order => :id )

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @races }
    end
  end

  # GET /races/1
  # GET /races/1.json
  def show
    @race = Race.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @race }
    end
  end

  # GET /races/new
  # GET /races/new.json
  def new
    @race = Race.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @race }
    end
  end

  # GET /races/1/edit
  def edit
    @race = Race.find(params[:id])
  end

  # POST /races
  # POST /races.json
  def create
    @race = Race.new(params[:race])

    respond_to do |format|
      if @race.save
        format.html { redirect_to @race, notice: 'Race was successfully created.' }
        format.json { render json: @race, status: :created, location: @race }
      else
        format.html { render action: "new" }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /races/1
  # PUT /races/1.json
  def update
    @race = Race.find(params[:id])

    respond_to do |format|
      if @race.update_attributes(params[:race])
        format.html { redirect_to "/races/#{@race.id+1}/edit", notice: "Race #{@race.id} was successfully updated." }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1
  # DELETE /races/1.json
  def destroy
    @race = Race.find(params[:id])
    @race.destroy

    respond_to do |format|
      format.html { redirect_to races_url }
      format.json { head :ok }
    end
  end
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/races/_form.html.erb
<%= form_for(@race) do |f| %>
  <% if @race.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@race.errors.count, "error") %> prohibited this race from being saved:</h2>

      <ul>
      <% @race.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.hidden_field :heat %>
  <div class="field">
    <b>Left / Yellow Lane</b><br />
    <%= @race.scout_1.name %>'s time: <%= f.number_field :time1 %><br />
    <%= f.hidden_field :scout_1_id %>
  </div>
  <div class="field">
    <b>Right / Blue Lane</b><br />
    <%= @race.scout_2.name %>'s time: <%= f.number_field :time2 %><br />
    <%= f.hidden_field :scout_2_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<% set_focus_to_id 'race_time1' %>

app/views/races/edit.html.erb
<h1>Race <%= @race.id %></h1>

<p id="notice"><%= notice %></p>

<%= render 'form' %>

<%= link_to 'Previous', "/races/#{@race.id-1}/edit" %> |
<%= link_to 'List', races_path %> | 
<%= link_to 'Next', "/races/#{@race.id+1}/edit" %>

app/views/races/index.html.erb
<h1>Races</h1>

<table>
  <tr>
    <th>Race</th>
    <th>&nbsp;</th>
    <th>Left Lane</th>
    <th>Time</th>
    <th>&nbsp;</th>
    <th>Right Lane</th>
    <th>Time</th>
    <th>&nbsp;</th>
    <th>Winner</th>
    <th></th>
  </tr>

<% @races.each do |race| %>
  <tr>
    <td><%= race.id %></td>
    <td>&nbsp;</td>
    <td><%= race.scout_1.name %></td>
    <td><%= race.time1 %></td>
    <td>&nbsp;</td>
    <td><%= race.scout_2.name %></td>
    <td><%= race.time2 %></td>
    <td>&nbsp;</td>
    <td><%= race.winner_name %></td>
    <td><%= link_to 'edit', edit_race_path(race) %></td>
  </tr>
<% end %>
</table>

<br />

app/views/races/new.html.erb
<h1>New race</h1>

<%= render 'form' %>

<%= link_to 'Back', races_path %>

app/views/races/show.html.erb
<p id="notice"><%= notice %></p>

<p><b>Left / Yellow Lane</b><br />
  <%= @race.scout_1.name %>'s time = 
  <%= @race.time1 %>
</p>

<p><b>Right / Blue Lane</b><br />
  <%= @race.scout_2.name %>'s time =
  <%= @race.time2 %>
</p>

<%= link_to 'Previous', "/races/#{@race.id-1}/edit" %> |
<%= link_to 'Edit', edit_race_path(@race) %> |
<%= link_to 'List', races_path %> | 
<%= link_to 'Next', "/races/#{@race.id+1}/edit" %>