config/routes.rb
PinewoodDerby::Application.routes.draw do
  resources :summaries

  resources :races

  resources :scouts

end

app/models/scout.rb
class Scout < ActiveRecord::Base
end

app/controllers/scouts_controller.rb
class ScoutsController < ApplicationController
  # GET /scouts
  # GET /scouts.json
  def index
    @scouts = Scout.find( :all, :order => :name )
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @scouts }
    end
  end

  # GET /scouts/1
  # GET /scouts/1.json
  def show
    @scout = Scout.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @scout }
    end
  end

  # GET /scouts/new
  # GET /scouts/new.json
  def new
    @scout = Scout.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @scout }
    end
  end

  # GET /scouts/1/edit
  def edit
    @scout = Scout.find(params[:id])
  end

  # POST /scouts
  # POST /scouts.json
  def create
    @scout = Scout.new(params[:scout])

    respond_to do |format|
      if @scout.save
        format.html { redirect_to @scout, notice: 'Scout was successfully created.' }
        format.json { render json: @scout, status: :created, location: @scout }
      else
        format.html { render action: "new" }
        format.json { render json: @scout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /scouts/1
  # PUT /scouts/1.json
  def update
    @scout = Scout.find(params[:id])

    respond_to do |format|
      if @scout.update_attributes(params[:scout])
        format.html { redirect_to @scout, notice: 'Scout was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @scout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scouts/1
  # DELETE /scouts/1.json
  def destroy
    @scout = Scout.find(params[:id])
    @scout.destroy

    respond_to do |format|
      format.html { redirect_to scouts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/scouts_helper.rb
module ScoutsHelper
end

app/views/scouts/_form.html.erb
<%= form_for(@scout) do |f| %>
  <% if @scout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scout.errors.count, "error") %> prohibited this scout from being saved:</h2>

      <ul>
      <% @scout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :car %><br />
    <%= f.text_field :car %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scouts/edit.html.erb
<h1>Editing scout</h1>

<%= render 'form' %>

<%= link_to 'Show', @scout %> |
<%= link_to 'Back', scouts_path %>

app/views/scouts/index.html.erb
<h1>Pack 353</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Car</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @scouts.each do |scout| %>
  <tr>
    <td><%= scout.name %></td>
    <td><%= scout.car %></td>
    <td><%= link_to 'Show', scout %></td>
    <td><%= link_to 'Edit', edit_scout_path(scout) %></td>
    <td><%= link_to 'Destroy', scout, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<% if false then %>
<%= link_to 'New Scout', new_scout_path %>
<% end %>

app/views/scouts/new.html.erb
<h1>New scout</h1>

<%= render 'form' %>

<%= link_to 'Back', scouts_path %>

app/views/scouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @scout.name %>
</p>

<p>
  <b>Car:</b>
  <%= @scout.car %>
</p>


<%= link_to 'Edit', edit_scout_path(@scout) %> |
<%= link_to 'Back', scouts_path %>